// Writes firebaseConfig.js + google client id from environment variables (GitHub Actions / CI).
// Run: node write-config.js
// Env vars (all optional):
//   FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_PROJECT_ID, FIREBASE_STORAGE_BUCKET,
//   FIREBASE_MESSAGING_SENDER_ID, FIREBASE_APP_ID
//   GOOGLE_CLIENT_ID

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const cfg = `// Firebase configuration (auto-generated by write-config.js from env vars)
export const firebaseConfig = {
  apiKey: ${JSON.stringify(process.env.FIREBASE_API_KEY || 'YOUR_FIREBASE_API_KEY')},
  authDomain: ${JSON.stringify(process.env.FIREBASE_AUTH_DOMAIN || 'YOUR_PROJECT.firebaseapp.com')},
  projectId: ${JSON.stringify(process.env.FIREBASE_PROJECT_ID || 'YOUR_PROJECT_ID')},
  storageBucket: ${JSON.stringify(process.env.FIREBASE_STORAGE_BUCKET || 'YOUR_PROJECT.appspot.com')},
  messagingSenderId: ${JSON.stringify(process.env.FIREBASE_MESSAGING_SENDER_ID || 'YOUR_SENDER_ID')},
  appId: ${JSON.stringify(process.env.FIREBASE_APP_ID || 'YOUR_APP_ID')},
};

export const FIREBASE_ENABLED = firebaseConfig.apiKey !== "YOUR_FIREBASE_API_KEY";
`;

const google = `// Google OAuth Login (for Android / Web standalone app)
const GOOGLE_CLIENT_ID = ${JSON.stringify(process.env.GOOGLE_CLIENT_ID || 'YOUR_GOOGLE_WEB_CLIENT_ID.apps.googleusercontent.com')};

export const googleService = {
  clientId: GOOGLE_CLIENT_ID,
  loadScript: () => {
    return new Promise((resolve, reject) => {
      if (window.google && window.google.accounts && window.google.accounts.oauth2) {
        resolve();
        return;
      }
      const existing = document.getElementById('google-identity-script');
      if (existing) {
        existing.addEventListener('load', () => resolve());
        return;
      }
      const script = document.createElement('script');
      script.id = 'google-identity-script';
      script.src = 'https://accounts.google.com/gsi/client';
      script.async = true;
      script.defer = true;
      script.onload = () => resolve();
      script.onerror = () => reject(new Error('Failed to load Google script'));
      document.head.appendChild(script);
    });
  },

  signIn: () => {
    return new Promise(async (resolve, reject) => {
      try {
        await googleService.loadScript();
        const client = window.google.accounts.oauth2.initTokenClient({
          client_id: GOOGLE_CLIENT_ID,
          scope: 'email profile openid',
          callback: async (response) => {
            if (response.error) {
              reject(new Error(response.error));
              return;
            }
            try {
              const res = await fetch('https://www.googleapis.com/oauth2/v3/userinfo', {
                headers: { Authorization: \`Bearer \${response.access_token}\` },
              });
              const profile = await res.json();
              resolve({
                id: profile.sub,
                email: profile.email,
                name: profile.name,
                firstName: profile.given_name || profile.name,
                lastName: profile.family_name || '',
                photoURL: profile.picture,
                username: profile.email ? profile.email.split('@')[0] : '',
              });
            } catch (e) {
              reject(e);
            }
          },
        });
        client.requestAccessToken();
      } catch (e) {
        reject(e);
      }
    });
  },
};
`;

const outDir = path.join(__dirname, 'src', 'services');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'firebaseConfig.js'), cfg);
fs.writeFileSync(path.join(outDir, 'google.js'), google);
console.log('Config written. FIREBASE_ENABLED =', cfg.includes('YOUR_FIREBASE_API_KEY') ? 'false' : 'true');
