// Writes firebaseConfig.js + google client id from environment variables (GitHub Actions / CI).
// Run: node write-config.js
// Env vars (all optional):
//   FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_PROJECT_ID, FIREBASE_STORAGE_BUCKET,
//   FIREBASE_MESSAGING_SENDER_ID, FIREBASE_APP_ID
//   GOOGLE_CLIENT_ID

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const cfg = `// Firebase configuration (auto-generated by write-config.js from env vars)
export const firebaseConfig = {
  apiKey: ${JSON.stringify(process.env.FIREBASE_API_KEY || 'YOUR_FIREBASE_API_KEY')},
  authDomain: ${JSON.stringify(process.env.FIREBASE_AUTH_DOMAIN || 'YOUR_PROJECT.firebaseapp.com')},
  projectId: ${JSON.stringify(process.env.FIREBASE_PROJECT_ID || 'YOUR_PROJECT_ID')},
  storageBucket: ${JSON.stringify(process.env.FIREBASE_STORAGE_BUCKET || 'YOUR_PROJECT.appspot.com')},
  messagingSenderId: ${JSON.stringify(process.env.FIREBASE_MESSAGING_SENDER_ID || 'YOUR_SENDER_ID')},
  appId: ${JSON.stringify(process.env.FIREBASE_APP_ID || 'YOUR_APP_ID')},
};

export const FIREBASE_ENABLED = firebaseConfig.apiKey !== "YOUR_FIREBASE_API_KEY";
`;

const google = `import { GoogleAuth } from '@codetrix-studio/capacitor-google-auth';

const GOOGLE_CLIENT_ID = ${JSON.stringify(process.env.GOOGLE_CLIENT_ID || 'YOUR_GOOGLE_WEB_CLIENT_ID.apps.googleusercontent.com')};

export const googleService = {
  clientId: GOOGLE_CLIENT_ID,

  initialize: () => {
    try {
      GoogleAuth.initialize({
        clientId: GOOGLE_CLIENT_ID,
        scopes: ['profile', 'email'],
        grantOfflineAccess: true,
      });
    } catch (e) {
      console.warn('GoogleAuth initialize warning:', e);
    }
  },

  signIn: async () => {
    try {
      googleService.initialize();
      const result = await GoogleAuth.signIn();
      const user = result.user;
      if (!user || !user.id) throw new Error('Google login failed - no user data');
      return {
        id: user.id,
        email: user.email,
        name: user.name || user.email,
        firstName: user.givenName || user.name || '',
        lastName: user.familyName || '',
        photoURL: user.imageUrl || null,
        username: user.email ? user.email.split('@')[0] : '',
      };
    } catch (e) {
      throw new Error(e.message || 'Google login failed');
    }
  },
};
`;

const outDir = path.join(__dirname, 'src', 'services');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'firebaseConfig.js'), cfg);
fs.writeFileSync(path.join(outDir, 'google.js'), google);
console.log('Config written. FIREBASE_ENABLED =', cfg.includes('YOUR_FIREBASE_API_KEY') ? 'false' : 'true');
